### ISSUE TITLE
Deployment questions

### ISSUE THREAD

**Issue by acamilleri** [sp-yduck/cloud-provider-proxmox#6]
Hello,

Next use your project in my homelab, I have some questions about CCM deployment.
I did not make a pull request for these CCM deployment issues, but if you agree with me, I can do that for you. But I want your opinion first.

### About the nodeSelector
The [CCM deployment manifest](https://github.com/k8s-proxmox/cloud-provider-proxmox/blob/master/manifests/cloud-controller-manager.yaml#L74-L75) includes a `nodeSelector` to avoid scheduling the CCM on control plane nodes, but the CCM is required to allow pod scheduling by removing the `node.cloudprovider.kubernetes.io/uninitialized` taint during the control plane initialization.
```
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
```

My understanding is that the CCM is a system component and it can be a part of the control plane, but I may have a misunderstanding, what's your opinion?

### About the deployment as daemonset

Do you have a reason to run the CCM as a daemonset ? My opinion is to switch to a deployment to avoid wasting resources, and a user can replicate it as he wants in a larger cluster. What's your opinion ?

**Comment by sp-yduck** [comment]
yes ccm is a part of control-plane component (https://kubernetes.io/docs/concepts/architecture/cloud-controller/) and that nodeSelector is to schedule ccm on control plane (maybe the value `""` of it is confusing you ?)

about the daemonset, I think that is officially recommended way as you can see in this example : https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#cloud-controller-manager

**Comment by acamilleri** [comment]
Yes, the `""` value and it's very strange because with this configuration the pod is not scheduled in my env. I will check why.

About the daemonset you are right, the documentation point to deploy it as daemonset, I'm not really enjoy with that, I just edit this on my side ^^'

Thanks for explanations !
